### ISSUE TITLE
Attempting to build Main.agda with README instructions gives error for agda version 2.6.1.2

### ISSUE THREAD

**Issue by enlambdment** [halfaya/MusicTools#1]
I am currently using Agda version 2.6.1.2 which appears to be the latest official version as of this time (going by [Hackage](https://hackage.haskell.org/package/Agda) .)

`$ agda --version
Agda version 2.6.1.2`

I cloned this repo, tried once to run `agda -c Main.agda`, then used [agda-pkg](https://agda.github.io/agda-pkg/#/)  to install `cubical` once I found that it is a dependency for `MusicTools`. (I have made sure to replace the hard-coded `file` path with my own.)

When running `agda -c Main.agda`, I receive this error message:

> Checking Main (/Users/[my name]/Desktop/agda_work/MusicTools/agda/Main.agda).
 Checking Midi (/Users/[my name]/Desktop/agda_work/MusicTools/agda/Midi.agda).
  Checking Pitch (/Users/[my name]/Desktop/agda_work/MusicTools/agda/Pitch.agda).
   Checking BitVec (/Users/[my name]/Desktop/agda_work/MusicTools/agda/BitVec.agda).
/Users/[my name]/Desktop/agda_work/MusicTools/agda/BitVec.agda:19,14-18
(ℓ : Cubical.Core.Everything.Level) →
Set (Cubical.Core.Everything.ℓ-suc ℓ)
should be a sort, but it isn't
when checking that the expression Type has type _1

**Comment by halfaya** [comment]
Hi, I'm using the development version of Agda and some version of Cubical that may be a little old. My guess is that something changed in Cubical and you can no longer just write "Type" but need to say "Type0" or something like that. I'll update Cubical in the next few days and see if I run into the problem. For now you can fix it locally if you care to.

**Comment by halfaya** [comment]
I upgraded to the latest development version of Agda, and latest stdlib and cubical libraries and everything works fine. Since this is still a personal project in an early stage I'm unable to support anything except my own environment.
